apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - endpoints
  - services
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  verbs:
  - create
  - get 
  - update
  resources:
  - prometheuses/api
  resourceNames:
  - k8s
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
