apiVersion: v1
kind: ConfigMap
metadata:
  name: general-alerts
  namespace: prometheus
data:
  general-alerts.yaml: |
    groups:
    - name: persistent-voluume-80
      rules:
      - alert: persistent-voluume-80
        expr: 100 - kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes * 100 > 10
        for: 10m
        annotations:
          message: volume creater than 10
        labels:
          severity: warning
          clustername: prom
    - name: vector
      rules:
      - alert: vector
        expr: vector(1)
        for: 1m
        annotations:
          message: "alerting is enabled on {{ $externalLabels.clustername }}"
        labels:
          severity: critical
