apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alertmanager
  name: alertmanager
  namespace: prometheus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alertmanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alertmanager
    spec:
      containers:
      - args:
        - --storage.path=/alertmanager
        - --web.listen-address=:9093
        image: registry.redhat.io/openshift4/ose-prometheus-alertmanager-rhel9:latest
        imagePullPolicy: Always
        name: alertmanager
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /alertmanager
          name: alertmanager
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: alertmanager
      terminationGracePeriodSeconds: 30
      volumes:
      - name: alertmanager
        persistentVolumeClaim:
          claimName: alertmanager