apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: alertmanager
  namespace: prometheus
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem