apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager
  namespace: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
