apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: prometheus
spec:
  host: prometheus.apps.rosa.prometheus.jgsh.p3.openshiftapps.com
  port:
    targetPort: 9090-9090
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: prometheus
    weight: 100
  wildcardPolicy: None