apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: prometheus
  name: prometheus-service-account-token
  namespace: prometheus
type: kubernetes.io/service-account-token
