apiVersion: v1
kind: ServiceAccount
metadata:
  #annotations:
    #add a role here to use SNS
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"alertmanager"}}'
  name: alertmanager
  namespace: prometheus
